#!/bin/bash

cd /Volumes/Xcode\ Project/AppLocker/Launcher
find . -name '.DS_Store' -type f -delete
echo Starting Packaging Installer...
echo 
mkdir -p AppLocker_Pkg/Package/
pkgbuild \
  --root AppLocker_Pkg/Installer/root \
  --identifier com.TranPhuong319.AppLocker-Installer \
  --version 1.2.0 \
  --scripts AppLocker_Pkg/Installer/scripts \
  --install-location / \
  AppLocker_Pkg/Package/Installer.pkg

echo Starting Packaging Uninstaller...
echo 
pkgbuild \
  --nopayload \
  --identifier com.TranPhuong319.AppLocker-Uninstaller \
  --scripts AppLocker_Pkg/Uninstaller/scripts \
  AppLocker_Pkg/Package/Uninstall.pkg

echo Starting Packaging Product...
echo
mkdir -p Product
productbuild \
  --distribution AppLocker_Pkg/Distribution.xml \
  --resources AppLocker_Pkg/Resources \
  --package-path AppLocker_Pkg/Package/ \
  Product/AppLockerInstaller.pkg

echo Generating checksums...
OUTPUT="Product/checksums.txt"
echo "-----------------------------------------------" > $OUTPUT
for file in Product/*.pkg; do
    if [ -f "$file" ]; then
        echo "File: $(basename "$file")" >> $OUTPUT
        echo "SHA256:" >> $OUTPUT
        shasum -a 256 "$file" >> $OUTPUT
        echo "MD5:" >> $OUTPUT
        md5 "$file" >> $OUTPUT
        echo "-----------------------------------------------" >> $OUTPUT
    fi
done

echo "✅ Packaging completed. Checksums saved in $OUTPUT"
