#!/bin/zsh --no-rcs

cd /Volumes/Xcode\ Project/AppLocker/Launcher
echo
echo Generating checksums...
OUTPUT="Product/checksums.txt"
echo "-----------------------------------------------" > $OUTPUT
for file in Product/*.pkg; do
    if [ -f "$file" ]; then
        echo "File: $(basename "$file")" >> $OUTPUT
        echo "SHA256:" >> $OUTPUT
        shasum -a 256 "$file" >> $OUTPUT
        echo "MD5:" >> $OUTPUT
        md5 "$file" >> $OUTPUT
        echo "-----------------------------------------------" >> $OUTPUT
    fi
done

echo "✅ Packaging completed. Checksums saved in $OUTPUT"
